-- 聊天记录分表（仅本地开发用；生产由业务方/DBA 建表）。
-- 由 docker MySQL 初始化时执行；应用代码不再建表。
USE chat_summary;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_1` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_2` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_3` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_4` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_5` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_6` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_7` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_8` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_9` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_10` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_11` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_12` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_13` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_14` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_15` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_16` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_17` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_18` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_19` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `user_chat_record_sharding_20` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息唯一标识',
  `content` text COLLATE utf8mb4_bin NOT NULL COMMENT '消息内容',
  `create_date` date NOT NULL COMMENT '创建日期',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `msg_time` datetime NOT NULL COMMENT '消息发送时间',
  `from_user` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '发送用户',
  `to_user` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '接收用户',
  `room_id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '群聊ID',
  `msg_type` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '消息类型',
  `db_time` datetime DEFAULT NULL COMMENT '数据库记录时间',
  `msg_time_long` bigint DEFAULT '1774972800000' COMMENT '消息时间戳（毫秒）',
  `msg_body` text COLLATE utf8mb4_bin COMMENT '消息体内容',
  `action_text` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作文本',
  `scene` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '场景',
  PRIMARY KEY (`id`),
  KEY `idx_from_user` (`from_user`),
  KEY `idx_msg_time` (`msg_time`),
  KEY `idx_msgtime_long` (`msg_time_long`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_to_user` (`to_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

